### ISSUE TITLE
Issue on NLTK Downloader to obtain the resource

### ISSUE THREAD

**Issue by orchestor** [keonkim/CodeGAN#1]
could you point out how to get the resource?

~~~~~~~~~~~~~~~~~`
Traceback (most recent call last):
  File "pretrain_experiment.py", line 136, in <module>
    main()
  File "pretrain_experiment.py", line 82, in main
    stringGenerator = TextGenerator('../corpus/index2word.pickle', '../corpus/word2index.pickle', '../corpus/all.code')
  File "/Users/grant/project/CodeGAN/codegan-pg/text_generator.py", line 25, in __init__
    words = nltk.word_tokenize(self.spacer(content))
  File "/Users/grant/project/CodeGAN/codegan/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 109, in word_tokenize
    return [token for sent in sent_tokenize(text, language)
  File "/Users/grant/project/CodeGAN/codegan/lib/python2.7/site-packages/nltk/tokenize/__init__.py", line 93, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/Users/grant/project/CodeGAN/codegan/lib/python2.7/site-packages/nltk/data.py", line 808, in load
    opened_resource = _open(resource_url)
  File "/Users/grant/project/CodeGAN/codegan/lib/python2.7/site-packages/nltk/data.py", line 926, in _open
    return find(path_, path + ['']).open()
  File "/Users/grant/project/CodeGAN/codegan/lib/python2.7/site-packages/nltk/data.py", line 648, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource u'tokenizers/punkt/english.pickle' not found.  Please
  use the NLTK Downloader to obtain the resource:  >>>
  nltk.download()
  Searched in:
    - '/Users/grant/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - u''
**********************************************************************

**Comment by keon** [comment]
try this:
in a python shell:
```
>> import nltk
>> nltk.download()
# and then type 'd' for download and install 'punkt'
```

**Comment by orchestor** [comment]
Thanks. It works now.

**Comment by chanduthedev** [comment]
I am also facing same issue and I got certificate failure as below. Can you please suggest any alternative for this?

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

**Comment by SharanSMenon** [comment]
> I am also facing same issue and I got certificate failure as below. Can you please suggest any alternative for this?
> 
> [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)

I also get that same issue

**Comment by gaganc** [comment]
i was getting the same SSL:CETIFICATE_VERIFY_FAILED. On MacOS running the following command fixed it (match the path to your version of python)
_/Applications/Python 3.6/Install Certificates.command_

**Comment by HaticeKubraKilinc** [comment]
nltk.download() 
when I write this my computer shutdown suddenly (Macbook pro 2018)
Why is  this happening ? and How can I solve it ?
Also anaconda is closing and when I try to open I take a message like already it open :/

**Comment by syomantak** [comment]
@keon Do you have any idea what to do in colab? Can't really give an input in notebook :(

**Comment by HaticeKubraKilinc** [comment]
> @keon Do you have any idea what to do in colab? Can't really give an input in notebook :(

I am not fully understand what's your problem but I 'm gonna share how I solved my issue; instead of download whole nltk I download directly to what I need namely I wrote like nltk.download(“something that I need”)
And this style solved my issue

**Comment by zyzeat** [comment]
> > @keon Do you have any idea what to do in colab? Can't really give an input in notebook :(
> 
> I am not fully understand what's your problem but I 'm gonna share how I solved my issue; instead of download whole nltk I download directly to what I need namely I wrote like nltk.download(“something that I need”)
> And this style solved my issue

hello！I have the same problem. When I want to use it, my computer suddenly restarts, and nltk.download("something") isn't work.

**Comment by juangina** [comment]
> try this:
> in a python shell:
> 
> ```
> >> import nltk
> >> nltk.download()
> # and then type 'd' for download and install 'punkt'
> ```

Thanks

**Comment by juangina** [comment]
> > try this:
> > in a python shell:
> > ```
> > >> import nltk
> > >> nltk.download()
> > # and then type 'd' for download and install 'punkt'
> > ```
> 
> Thanks

Also had to repeat for (;wordnet') and ('average_perceptron_tagger')
